language: go
go:
- '1.12.x'

sudo: required

services:
  - docker

before_install:
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - cd ecr-login && shopt -s globstar
  - sed -i 's/github.com\/awslabs\/amazon-ecr-credential-helper/github.com\/seanturner83\/amazon-ecr-credential-helper/g' **/*.go && cd ..
  - go get -t -v ./...
  - cd ecr-login/cli && CGO_ENABLED=0 gox -os="linux darwin windows" -arch="amd64" -verbose ./docker-credential-ecr-login
  - cd ../..

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AAoVb/KhpFiNhxrqRS9fCe1Sjn6/wcBy61jqFL8Wlb/YF0rlY5sapslTYRenANbo+WvvAzgHorEkKdpFsFfUG1LFgnqeQzUAAgtbHdJbyPaT6yZZQWLlBO5YOJWWz0J9HAgHI+tcGctQ67VcCPTs3ouTsGL70OMMmsvUZnpPb69ghJ9HvPkPlUSqs4/ZVq5fja3EJuaF28z2l7dlt4euZCTGBoIAeF1e87OdqsAak1EQgDHNWQ/rJORIiR/FAiyYgOrGcdpdZVrUda639vM4rM1u5/scOY8+XZ0G2TUzivU5tmFD1swRFo+jF8UJFnke2d2yw71qmPdFzunRylVA9vdNbjTdU0JKHM7gO4eXu9Nz7CP74VqYVRtPUEmwASfTtJOXfTqI8SRJPXxtySjQbgvSSytkvQ+wRCNmVWjZYhHHJHGknXbW0MNIH6i+EKmi67rPq1CNbvywKEHVGZvl1fOh/Gv2e9U8l5G+azpHhBZ5nc7uSR+eShFodTiWs5lahRa4P5UvviBvs2vHRy2Z/KxGEkp7vZ8mKe1u2M9pmrULOB6B/Qjb55ePuAPRVqL0nDGBPzXa4e1jTTrUke3mQGPtBAtQBjqwrxLAVUtaJDBLxYaq36n+u1nPtgHMI8nOfnTStkXVgXElSj4iA6H2GRmtko+yxGWnJmAkRSVLWy4=
  file: 
  - login/cli/docker-credential-ecr-login_darwin_amd64
  - login/cli/docker-credential-ecr-login_linux_amd64
  - login/cli/docker-credential-ecr-login_windows_amd64.exe
  on:
    repo: seanturner83/amazon-ecr-credential-helper
    all_branches: true

after_deploy:
 - ls -al
 - docker build -t seanturner83/amazon-ecr-credential-helper:${TRAVIS_TAG} -f Dockerfile .
 - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
 - docker push "seanturner83/amazon-ecr-credential-helper:${TRAVIS_TAG}"
